import { defineConfig } from 'oxlint'

export default defineConfig({
  plugins: ['eslint', 'import', 'promise', 'typescript', 'unicorn', 'vitest'],
  rules: {
    'no-unused-vars': 'error',
    'no-undef': 'error',
    'no-unused-private-class-members': 'error',
    'no-param-reassign': 'error',
    'yoda': 'error',
    'curly': 'error',
    'no-negated-condition': 'error',
    'default-param-last': 'error',
    'no-empty': 'error',
    'eqeqeq': 'error',
    'no-var': 'error',
    'prefer-const': 'error',
    'no-throw-literal': 'error',
    'no-self-compare': 'error',
    'no-useless-constructor': 'error',
    'no-array-constructor': 'error',
    'no-new-wrappers': 'error',
    'no-object-constructor': 'error',
    'no-return-assign': 'error',
    'no-sequences': 'error',
    'no-template-curly-in-string': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unreachable': 'error',
    'no-fallthrough': 'error',
    'no-case-declarations': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-lone-blocks': 'error',
    'no-new-func': 'error',
    'no-new': 'error',
    'no-proto': 'error',
    'no-labels': 'error',
    'no-multi-str': 'error',
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-return': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'getter-return': 'error',
    'no-unexpected-multiline': 'error',
    'no-unneeded-ternary': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'symbol-description': 'error',
    'accessor-pairs': 'error',
    'new-cap': 'error',
    'array-callback-return': 'error',
    'prefer-promise-reject-errors': 'error',
    'no-useless-escape': 'error',
    'import/extensions': ['error', 'always', { ignorePackages: true }],
    'import/no-namespace': 'error',
    'import/no-default-export': 'error',
    'import/no-named-as-default': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-absolute-path': 'error',
    'import/first': 'error',
    'import/no-duplicates': 'error',
    'import/no-self-import': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-inferrable-types': 'error',
    'typescript/array-type': ['error', { default: 'array' }],
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-enum-initializers': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-extraneous-class': 'error',
    'typescript/no-invalid-void-type': 'error',
    'typescript/no-non-null-assertion': 'error',
    'typescript/no-non-null-asserted-nullish-coalescing': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/ban-ts-comment': 'error',
    'typescript/no-dynamic-delete': 'error',
    'typescript/prefer-literal-enum-member': 'error',
    'typescript/unified-signatures': 'error',
    'typescript/prefer-for-of': 'error',
    'typescript/no-use-before-define': 'error',
    'promise/prefer-await-to-callbacks': 'error',
    'promise/prefer-await-to-then': 'error',
    'promise/param-names': 'error',
    'unicorn/prefer-number-properties': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'jest/max-nested-describe': 'error',
    'jest/no-hooks': 'error',
    'jest/no-commented-out-tests': 'error',
    'oxc/no-barrel-file': 'error'
  },
  overrides: [
    {
      files: ['*.config.*'],
      rules: {
        'import/no-default-export': 'off'
      }
    }
  ],
  ignorePatterns: ['build/**', 'node_modules/**']
})
